# Generated by Django 4.2.3 on 2024-06-10 16:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_color',
            field=colorfield.fields.ColorField(blank=True, default='#E91E63', image_field=None, max_length=25, samples=None),
        ),
    ]
