# Generated by Django 4.2.3 on 2024-06-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_chore_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
