# Generated by Django 4.2.3 on 2024-06-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chore_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='active',
        ),
    ]
