# Generated by Django 5.2.14 on 2026-06-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_last_notified_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notify_timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
