version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    networks:
      - default
    restart: unless-stopped
    ports:
      - 8081:8080
    image: lenorechore_frontend:development
    container_name: lenorechore_frontend_dev
    volumes:
      - ./frontend:/app
    env_file:
      - ./.env.dev
    environment:
      - NODE_ENV=development
      - TZ=America/New_York
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: /usr/src/app/start.dev.sh
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DEBUG=1
      - TZ=America/New_York
    ports:
      - 8001:8001
      - 8002:8002
    depends_on:
      - db
    networks:
      - default
    env_file:
      - ./.env.dev
    image: lenorechore_backend:development
    container_name: lenorechore_backend_dev
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: /usr/src/app/start_worker.sh
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DEBUG=1
      - TZ=America/New_York
    depends_on:
      - db
      - backend
    networks:
      - default
    env_file:
      - ./.env.dev
    image: lenorechore_worker:development
    container_name: lenorechore_worker_dev
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    networks:
      - default
    container_name: lenorechore_db_dev
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
      - TZ=America/New_York

volumes:
  postgres_data:
  static_volume:
  media_volume:
