version: "3.8"

services:
  frontend:
    build: ./frontend
    networks:
      - default
    restart: unless-stopped
    expose:
      - 80
    env_file:
      - ./.env.fe
    image: chores_frontend:production
    container_name: chores_frontend
  backend:
    build:
      context: ./backend
    command: /home/app/web/start.sh
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - default
    env_file:
      - ./.env
    image: chores_backend:production
    container_name: chores_backend
  worker:
    build:
      context: ./backend
    command: /home/app/web/start_worker.sh
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - db
      - backend
    networks:
      - default
    env_file:
      - ./.env
    image: chores_worker:production
    container_name: chores_worker
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backup:/backup
    env_file:
      - ./.env.db
    networks:
      - default
    container_name: chores_db
  nginx:
    image: registry.danielleandjohn.love/django_vue_proxy:latest
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - backend
      - frontend
    networks:
      - default
    ports:
      - 7000:80
    container_name: chores_proxy

volumes:
  postgres_data:
  static_volume:
  media_volume:
