services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /home/app/web/start.app.sh
    volumes:
      - data_volume:/home/app/web/data
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 7000:80
    depends_on:
      - db
      - redis
    networks:
      - default
    env_file:
      - ./.env
    image: lenorechore:production
    container_name: lenorechore
    environment:
      - DEBUG=0

  redis:
    image: redis:7-alpine
    networks:
      - default
    container_name: lenorechore_redis
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backup:/backup
    env_file:
      - ./.env
    networks:
      - default
    container_name: lenorechore_db
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

volumes:
  postgres_data:
  data_volume:
  static_volume:
  media_volume:
