name: Tests

on:
  pull_request:
    branches: [main, rc, beta, alpha]

jobs:
  backend:
    if: github.repository != 'Novanglus96/LenoreTemplate'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Run tests
        working-directory: backend
        run: pytest -q

  frontend:
    if: github.repository != 'Novanglus96/LenoreTemplate'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Run tests
        working-directory: frontend
        run: npm test
