name: Versioning

on:
  workflow_run:
    workflows:
      - "Deploy MkDocs to GitHub Pages"
    types:
      - completed

jobs:
  check-commit:
    runs-on: self-hosted
    steps:
      - name: Check commit message
        id: check_commit
        run: |
          msg="${{ github.event.head_commit.message }}"
          echo "Commit message: $msg"
          
          if echo "$msg" | grep -Eiq '^(docs|ci):'; then
            echo "Excluded commit prefix found. Skipping workflow."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
  versioning:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Run Versioning Script
        run: |
          chmod +x scripts/versioning.sh
          ./scripts/versioning.sh
